### ISSUE TITLE
Alignment of navigation bullets is of in some browsers.

### ISSUE THREAD

**Issue by terw-dan** [Yoast/yoast-components#76] opened 2016-09-15 11:10 UTC
When the standalone onboard wizard is running in a very small viewport:
![image](https://cloud.githubusercontent.com/assets/11272096/18545442/7ec23db2-7b39-11e6-9683-df95680d9f88.png)
The colored bullet has a strange alignment. Also the texts are missing (is this intended?). 
![image](https://cloud.githubusercontent.com/assets/11272096/18545514/c56781d2-7b39-11e6-9ba7-0af50ca880cd.png)
Also on wider viewports.

This is in FireFox in Ubuntu. 

Chromium in Ubuntu has it's alignment better, and visible text in it's smallest viewports. 
![image](https://cloud.githubusercontent.com/assets/11272096/18545617/38392c2e-7b3a-11e6-956d-99391fc08e14.png)

But the grey line is running through the text.

**Comment by afercia** [comment] 2016-09-15 14:18
Re: alignment. Reproduced on Firefox. Looks like the whole "stepper" container is a bit taller than in Chrome. Checking better, the active button has some white space at the bottom: see in the screenshot below where there's a "gap" between the "pulsing circle" and the white box. This gap doesn't appear on Chrome...

![screen shot 2016-09-15 at 15 52 45](https://cloud.githubusercontent.com/assets/1682452/18553030/43f27eb0-7b5f-11e6-8f76-31f13645d4b7.png)

Quick fix: the buttons are currently set to `display: inline-block;` so there's some descender space that browsers usually reserve for any "inline" elements. Either set the button to `display: block` or better just apply `vertical-align: middle` seems to fix it.

**Comment by atimmer** [comment] 2016-09-22 12:44
Closed in #80

**Closed by atimmer** 2016-09-22 12:44 UTC
Labels: acceptance, UI
