### ISSUE TITLE
Insights messages and heading are not translatable

### ISSUE THREAD

**Issue by andizer** [Yoast/yoast-components#490] opened 2018-05-02 13:54 UTC
Copy from: https://github.com/Yoast/yoast-premium-components/issues/39

The messages about the Insights and the 'Insights' heading itself are not translatable. 

<img width="667" alt="schermafbeelding 2017-12-19 om 12 18 08" src="https://user-images.githubusercontent.com/17744553/34154964-cb8cc890-e4b7-11e7-9faf-e6c3cbde92c1.png">
<img width="646" alt="schermafbeelding 2017-12-19 om 12 22 03" src="https://user-images.githubusercontent.com/17744553/34154965-cba0a3ba-e4b7-11e7-86d2-e8406a532fb6.png">

**Comment by IreneStr** [comment] 2018-08-27 12:59
Duplicate of https://github.com/Yoast/yoast-components/issues/656

**Closed by IreneStr** 2018-08-27 12:59 UTC
